Repository chroventer/endb, pull requests merged in 2020-03, with the labels that each got.

#37 chore(docs.js): enrich the configuration for doc
  docs.js
Labels: enhancement

#38 Fix Connection Error: null
  src/adapters/leveldb.js
Labels: p: medium, type: bug

#40 chore(adapters): switch from events.EventEmitter
  src/adapters/leveldb.js
  src/adapters/mongodb.js
  src/adapters/redis.js
  src/adapters/sql.js
Labels: p: medium, type: refactor

#41 Add Endb#math
  package.json
  src/index.js
  src/util.js
  typings/index.d.ts
Labels: p: low, type: feature

#42 Endb#push: Allow duplicates elements in the array value of an element
  package.json
  src/index.js
  typings/index.d.ts
Labels: p: low, type: feature

#46 Introduce Iterators: keys(), values(), and entries()
  package.json
  src/index.js
Labels: p: high, type: feature

#47 Switch to lodash for extra path functionality
  package.json
  src/index.js
  src/util.js
Labels: p: medium, type: feature, type: refactor
