Repository chroventer/endb, pull requests merged in 2020-04, with the labels that each got.

#51 chore: setup commitlint
  package.json
Labels: type: feature

#53 feat: add connectTimeout option to mysql adapter
  src/adapters/mysql.js
Labels: p: low, type: feature

#55 Remove support for driver options from the main options
  src/adapters/mongodb.js
  src/adapters/mysql.js
  src/index.js
Labels: p: low, type: refactor

#56 feat: support for esm
  package.json
  src/index.mjs
Labels: p: low, type: feature

#57 docs(readme): follow the conventional readme format
  README.md
Labels: p: low, type: docs

#59 fix(endb#set): add prefix after _.set to avoid fallback
  src/index.js
Labels: p: medium, type: bugfix

#60 feat(endb#delete): path support for delete()
  package.json
  src/index.js
Labels: p: low, type: feature

#64 Add container name for each container
  docker-compose.yml
Labels: adapter: mongodb, adapter: mysql, adapter: postgresql, adapter: redis, adapter: sqlite, p: low, type: other
